---
- hosts: dockerhost
  tasks:
  - name: Stop existing container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: Delete existing container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: Delete existing image
    command: docker rmi dungdxd/devops-project-regapp:latest
    ignore_errors: yes

  - name: Run app
    command: docker run -d --name regapp-server -p 8082:8080 dungdxd/devops-project-regapp:latest